#!/usr/bin/python3
def raise_exception():
    raise TypeError("ca doit etre un nombre")
raise_exception()
